using DarkSoulsII.DebugView.Core.DarkSoulsII.Resources.Param.Character;

namespace DarkSoulsII.DebugView.Core.DarkSoulsII.Resources.Param.Containers
{
    public class CharacterParamContainer : IReadable<CharacterParamContainer>
    {
        public ParamFileResourceObjectForRegulation<ChrParam> ChrParam1 { get; set; }
        public ParamFileResourceObjectForRegulation<ChrCommonParam> ChrCommonParam1 { get; set; }
        public ParamFileResourceObjectForRegulation<ChrMoveParam> ChrMoveParam1 { get; set; }
        public ParamFileResourceObjectForRegulation<ChrEquipWeaponParam> ChrEquipWeaponParam1 { get; set; }
        public ParamFileResourceObjectForRegulation<ChrParam> ChrParam2 { get; set; }
        public ParamFileResourceObjectForRegulation<ChrCommonParam> ChrCommonParam2 { get; set; }
        public ParamFileResourceObjectForRegulation<ChrMoveParam> ChrMoveParam2 { get; set; }
        public ParamFileResourceObjectForRegulation<ChrEquipWeaponParam> ChrEquipWeaponParam2 { get; set; }
        public ParamFileResourceObjectForRegulation<PlayerCommonParam> PlayerCommonParam { get; set; }
        public ParamFileResourceObjectForRegulation<BehaviorParam> BehaviorParam1 { get; set; }
        public ParamFileResourceObjectForRegulation<BehaviorParam> BehaviorParam2 { get; set; }
        public ParamFileResourceObjectForRegulation<BehaviorParam> BehaviorParam3 { get; set; }
        public ParamFileResourceObjectForRegulation<ComboBehaviorParam> ComboBehaviorParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrColorParam> ChrColorParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrCullingParam> ChrCullingParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrEquipLoadParam> ChrEquipLoadParam { get; set; }
        public ParamFileResourceObjectForRegulation<FallingParam> FallingParam { get; set; }
        public ParamFileResourceObjectForRegulation<WeaponParam> WeaponParam { get; set; }
        public ParamFileResourceObjectForRegulation<WeaponActionCategoryParam> WeaponActionCategoryParam { get; set; }
        public ParamFileResourceObjectForRegulation<WeaponAttackMotionParam> WeaponAttackMotionParam { get; set; }
        public ParamFileResourceObjectForRegulation<WeaponTypeParam> WeaponTypeParam { get; set; }
        public ParamFileResourceObjectForRegulation<WeaponStaminaCostParam> WeaponStaminaCostParam { get; set; }
        public ParamFileResourceObjectForRegulation<WeaponReinforceParam> WeaponReinforceParam { get; set; }
        public ParamFileResourceObjectForRegulation<WeaponStatsAffectParam> WeaponStatsAffectParam { get; set; }
        public ParamFileResourceObjectForRegulation<DualWieldPermissionParam> DualWieldPermissionParam { get; set; }
        public ParamFileResourceObjectForRegulation<ArmorParam> ArmorParam { get; set; }
        public ParamFileResourceObjectForRegulation<ArmorReinforceParam> ArmorReinforceParam { get; set; }
        public ParamFileResourceObjectForRegulation<ArmorHandsUpFParam> ArmorHandsUpFParam { get; set; }
        public ParamFileResourceObjectForRegulation<EquipmentInterfereParam> EquipmentInterfereParam { get; set; }
        public ParamFileResourceObjectForRegulation<EquipmentCullingTargetParam> EquipmentCullingTargetParam { get; set;}
        public ParamFileResourceObjectForRegulation<CustomAttrSpecParam> CustomAttrSpecParam { get; set; }
        public ParamFileResourceObjectForRegulation<CustomAttrCostParam> CustomAttrCostParam { get; set; }
        public ParamFileResourceObjectForRegulation<ReinforceCostParam> ReinforceCostParam { get; set; }
        public ParamFileResourceObjectForRegulation<ArrowParam> ArrowParam { get; set; }
        public ParamFileResourceObjectForRegulation<RingParam> RingParam { get; set; }
        public ParamFileResourceObjectForRegulation<SpellParam> SpellParam { get; set; }
        public ParamFileResourceObjectForRegulation<SpellSoulConsumeParam> SpellSoulConsumeParam { get; set; }
        public ParamFileResourceObjectForRegulation<FootEffectSfxParam> FootEffectSfxParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrGrowthParam> ChrGrowthParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrLevelUpSoulsParam> ChrLevelUpSoulsParam { get; set; }
        public ParamFileResourceObjectForRegulation<RelatePhysStatToLevelStat> RelatePhysStatToLevelStat { get; set; }
        public ParamFileResourceObjectForRegulation<PhysStatsPerLevelStatParam> PhysStatsPerLevelStatParam { get; set; }
        public ParamFileResourceObjectForRegulation<MenuStatsParam> MenuStatsParam { get; set; }
        public ParamFileResourceObjectForRegulation<HollowLevelStatsParam> HollowLevelStatsParam { get; set; }
        public ParamFileResourceObjectForRegulation<LackOfStatsParam> LackOfStatsParam { get; set; }
        public ParamFileResourceObjectForRegulation<NpcGenerateParam> NpcGenerateParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrEditParamBodyPreset> ChrEditParamBodyPreset { get; set; }
        public ParamFileResourceObjectForRegulation<MaterialParam> MaterialParam { get; set; }
        public ParamFileResourceObjectForRegulation<GroundMaterialParam> GroundMaterialParam { get; set; }
        public ParamFileResourceObjectForRegulation<LockOnParam> LockOnParam { get; set; }
        public ParamFileResourceObjectForRegulation<LockTargetParam> LockTargetParam { get; set; }
        public ParamFileResourceObjectForRegulation<LockOnCameraOffsetParam> LockOnCameraOffsetParam { get; set; }
        public ParamFileResourceObjectForRegulation<GuardLevelMotionParam> GuardLevelMotionParam { get; set; }
        public ParamFileResourceObjectForRegulation<BossParam> BossParam { get; set; }
        public ParamFileResourceObjectForRegulation<BossPartsParam> BossPartsParam { get; set; }
        public ParamFileResourceObjectForRegulation<BossPartsModelParam> BossPartsModelParam { get; set; }
        public ParamFileResourceObjectForRegulation<BossEnemyGenerateParam> BossEnemyGenerateParam { get; set; }
        public ParamFileResourceObjectForRegulation<GrabParam> GrabParam { get; set; }
        public ParamFileResourceObjectForRegulation<DeadTypeParam> DeadTypeParam { get; set; }
        public ParamFileResourceObjectForRegulation<TorchCtrlParam> TorchCtrlParam { get; set; }
        public ParamFileResourceObjectForRegulation<TorchOffCtrlParam> TorchOffCtrlParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrWetParam> ChrWetParam { get; set; }
        public ParamFileResourceObjectForRegulation<HitBackMatrixParam> HitBackMatrixParam { get; set; }
        public ParamFileResourceObjectForRegulation<HitBackParam> HitBackParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrFullbodySfxParam> ChrFullbodySfxParam { get; set; }
        public ParamFileResourceObjectForRegulation<EnemyAttackMoveParam> EnemyAttackMoveParam { get; set; }
        public ParamFileResourceObjectForRegulation<PlayerStatusNormal> PlayerStatusNormal { get; set; }
        public ParamFileResourceObjectForRegulation<PlayerStatusItemParam> PlayerStatusItemParam { get; set; }
        public ParamFileResourceObjectForRegulation<NpcPlayerStatusParam> NpcPlayerStatusParam { get; set; }
        public ParamFileResourceObjectForRegulation<NpcPlayerSkinParam> NpcPlayerSkinParam { get; set; }
        public ParamFileResourceObjectForRegulation<CriminalAndDeceasedParam> CriminalAndDeceasedParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrPointWindParam> ChrPointWindParam { get; set; }
        public ParamFileResourceObjectForRegulation<PlayerLightParam> PlayerLightParam { get; set; }
        public ParamFileResourceObjectForRegulation<VowParam> VowParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrNetworkPhantomParam> ChrNetworkPhantomParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrNetPhantomSoulRateParam> ChrNetPhantomSoulRateParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrModelParam> ChrModelParam { get; set; }
        public ParamFileResourceObjectForRegulation<EnemyShotSfxParam> EnemyShotSfxParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrRoundDamageParam> ChrRoundDamageParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrRoundDropSoulParam> ChrRoundDropSoulParam { get; set; }
        public ParamFileResourceObjectForRegulation<ChrMultiplayParam> ChrMultiplayParam { get; set; }
        public ParamFileResourceObjectForRegulation<FootEffectWaterSfxParam> FootEffectWaterSfxParam { get; set; }

        public CharacterParamContainer Read(IPointerFactory pointerFactory, IReader reader, int address, bool relative = false)
        {
            // TODO: Refactor
            ChrParam1 = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrParam>>(address + 0x0000, relative).Unbox(pointerFactory, reader);
            ChrCommonParam1 = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrCommonParam>>(address + 0x0008, relative).Unbox(pointerFactory, reader);
            ChrMoveParam1 = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrMoveParam>>(address + 0x0010, relative).Unbox(pointerFactory, reader);
            ChrEquipWeaponParam1 = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrEquipWeaponParam>>(address + 0x0018, relative).Unbox(pointerFactory, reader);
            ChrParam2 = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrParam>>(address + 0x0020, relative).Unbox(pointerFactory, reader);
            ChrCommonParam2 = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrCommonParam>>(address + 0x0028, relative).Unbox(pointerFactory, reader);
            ChrMoveParam2 = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrMoveParam>>(address + 0x0030, relative).Unbox(pointerFactory, reader);
            ChrEquipWeaponParam2 = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrEquipWeaponParam>>(address + 0x0038, relative).Unbox(pointerFactory, reader);
            PlayerCommonParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<PlayerCommonParam>>(address + 0x0040, relative).Unbox(pointerFactory, reader);
            BehaviorParam1 = pointerFactory.Create<ParamFileResourceObjectForRegulation<BehaviorParam>>(address + 0x0048, relative).Unbox(pointerFactory, reader);
            BehaviorParam2 = pointerFactory.Create<ParamFileResourceObjectForRegulation<BehaviorParam>>(address + 0x0050, relative).Unbox(pointerFactory, reader);
            BehaviorParam3 = pointerFactory.Create<ParamFileResourceObjectForRegulation<BehaviorParam>>(address + 0x0058, relative).Unbox(pointerFactory, reader);
            ComboBehaviorParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ComboBehaviorParam>>(address + 0x0060, relative).Unbox(pointerFactory, reader);
            ChrColorParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrColorParam>>(address + 0x0068, relative).Unbox(pointerFactory, reader);
            ChrCullingParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrCullingParam>>(address + 0x0070, relative).Unbox(pointerFactory, reader);
            ChrEquipLoadParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrEquipLoadParam>>(address + 0x0078, relative).Unbox(pointerFactory, reader);
            FallingParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<FallingParam>>(address + 0x0080, relative).Unbox(pointerFactory, reader);
            WeaponParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<WeaponParam>>(address + 0x0088, relative).Unbox(pointerFactory, reader);
            WeaponActionCategoryParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<WeaponActionCategoryParam>>(address + 0x0090, relative).Unbox(pointerFactory, reader);
            WeaponAttackMotionParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<WeaponAttackMotionParam>>(address + 0x0098, relative).Unbox(pointerFactory, reader);
            WeaponTypeParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<WeaponTypeParam>>(address + 0x00A0, relative).Unbox(pointerFactory, reader);
            WeaponStaminaCostParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<WeaponStaminaCostParam>>(address + 0x00A8, relative).Unbox(pointerFactory, reader);
            WeaponReinforceParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<WeaponReinforceParam>>(address + 0x00B0, relative).Unbox(pointerFactory, reader);
            WeaponStatsAffectParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<WeaponStatsAffectParam>>(address + 0x00B8, relative).Unbox(pointerFactory, reader);
            DualWieldPermissionParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<DualWieldPermissionParam>>(address + 0x00C0, relative).Unbox(pointerFactory, reader);
            ArmorParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ArmorParam>>(address + 0x00C8, relative).Unbox(pointerFactory, reader);
            ArmorReinforceParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ArmorReinforceParam>>(address + 0x00D0, relative).Unbox(pointerFactory, reader);
            ArmorHandsUpFParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ArmorHandsUpFParam>>(address + 0x00D8, relative).Unbox(pointerFactory, reader);
            EquipmentInterfereParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<EquipmentInterfereParam>>(address + 0x00E0, relative).Unbox(pointerFactory, reader);
            EquipmentCullingTargetParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<EquipmentCullingTargetParam>>(address + 0x00E8, relative).Unbox(pointerFactory, reader);
            CustomAttrSpecParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<CustomAttrSpecParam>>(address + 0x00F0, relative).Unbox(pointerFactory, reader);
            CustomAttrCostParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<CustomAttrCostParam>>(address + 0x00F8, relative).Unbox(pointerFactory, reader);
            ReinforceCostParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ReinforceCostParam>>(address + 0x00100, relative).Unbox(pointerFactory, reader);
            ArrowParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ArrowParam>>(address + 0x00108, relative).Unbox(pointerFactory, reader);
            RingParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<RingParam>>(address + 0x00110, relative).Unbox(pointerFactory, reader);
            SpellParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<SpellParam>>(address + 0x00118, relative).Unbox(pointerFactory, reader);
            SpellSoulConsumeParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<SpellSoulConsumeParam>>(address + 0x00120, relative).Unbox(pointerFactory, reader);
            FootEffectSfxParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<FootEffectSfxParam>>(address + 0x00128, relative).Unbox(pointerFactory, reader);
            ChrGrowthParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrGrowthParam>>(address + 0x00130, relative).Unbox(pointerFactory, reader);
            ChrLevelUpSoulsParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrLevelUpSoulsParam>>(address + 0x00138, relative).Unbox(pointerFactory, reader);
            RelatePhysStatToLevelStat = pointerFactory.Create<ParamFileResourceObjectForRegulation<RelatePhysStatToLevelStat>>(address + 0x00140, relative).Unbox(pointerFactory, reader);
            PhysStatsPerLevelStatParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<PhysStatsPerLevelStatParam>>(address + 0x00148, relative).Unbox(pointerFactory, reader);
            MenuStatsParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<MenuStatsParam>>(address + 0x00150, relative).Unbox(pointerFactory, reader);
            HollowLevelStatsParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<HollowLevelStatsParam>>(address + 0x00158, relative).Unbox(pointerFactory, reader);
            LackOfStatsParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<LackOfStatsParam>>(address + 0x00160, relative).Unbox(pointerFactory, reader);
            NpcGenerateParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<NpcGenerateParam>>(address + 0x00168, relative).Unbox(pointerFactory, reader);
            ChrEditParamBodyPreset = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrEditParamBodyPreset>>(address + 0x00170, relative).Unbox(pointerFactory, reader);
            MaterialParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<MaterialParam>>(address + 0x00178, relative).Unbox(pointerFactory, reader);
            GroundMaterialParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<GroundMaterialParam>>(address + 0x00180, relative).Unbox(pointerFactory, reader);
            LockOnParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<LockOnParam>>(address + 0x00188, relative).Unbox(pointerFactory, reader);
            LockTargetParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<LockTargetParam>>(address + 0x00190, relative).Unbox(pointerFactory, reader);
            LockOnCameraOffsetParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<LockOnCameraOffsetParam>>(address + 0x00198, relative).Unbox(pointerFactory, reader);
            GuardLevelMotionParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<GuardLevelMotionParam>>(address + 0x001A0, relative).Unbox(pointerFactory, reader);
            BossParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<BossParam>>(address + 0x001A8, relative).Unbox(pointerFactory, reader);
            BossPartsParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<BossPartsParam>>(address + 0x001B0, relative).Unbox(pointerFactory, reader);
            BossPartsModelParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<BossPartsModelParam>>(address + 0x001B8, relative).Unbox(pointerFactory, reader);
            BossEnemyGenerateParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<BossEnemyGenerateParam>>(address + 0x001C0, relative).Unbox(pointerFactory, reader);
            GrabParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<GrabParam>>(address + 0x001C8, relative).Unbox(pointerFactory, reader);
            DeadTypeParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<DeadTypeParam>>(address + 0x001D0, relative).Unbox(pointerFactory, reader);
            TorchCtrlParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<TorchCtrlParam>>(address + 0x001D8, relative).Unbox(pointerFactory, reader);
            TorchOffCtrlParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<TorchOffCtrlParam>>(address + 0x001E0, relative).Unbox(pointerFactory, reader);
            ChrWetParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrWetParam>>(address + 0x001E8, relative).Unbox(pointerFactory, reader);
            HitBackMatrixParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<HitBackMatrixParam>>(address + 0x001F0, relative).Unbox(pointerFactory, reader);
            HitBackParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<HitBackParam>>(address + 0x001F8, relative).Unbox(pointerFactory, reader);
            ChrFullbodySfxParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrFullbodySfxParam>>(address + 0x00200, relative).Unbox(pointerFactory, reader);
            EnemyAttackMoveParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<EnemyAttackMoveParam>>(address + 0x00208, relative).Unbox(pointerFactory, reader);
            PlayerStatusNormal = pointerFactory.Create<ParamFileResourceObjectForRegulation<PlayerStatusNormal>>(address + 0x00210, relative).Unbox(pointerFactory, reader);
            PlayerStatusItemParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<PlayerStatusItemParam>>(address + 0x00218, relative).Unbox(pointerFactory, reader);
            NpcPlayerStatusParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<NpcPlayerStatusParam>>(address + 0x00220, relative).Unbox(pointerFactory, reader);
            NpcPlayerSkinParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<NpcPlayerSkinParam>>(address + 0x00228, relative).Unbox(pointerFactory, reader);
            CriminalAndDeceasedParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<CriminalAndDeceasedParam>>(address + 0x00230, relative).Unbox(pointerFactory, reader);
            ChrPointWindParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrPointWindParam>>(address + 0x00238, relative).Unbox(pointerFactory, reader);
            PlayerLightParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<PlayerLightParam>>(address + 0x00240, relative).Unbox(pointerFactory, reader);
            VowParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<VowParam>>(address + 0x00248, relative).Unbox(pointerFactory, reader);
            ChrNetworkPhantomParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrNetworkPhantomParam>>(address + 0x00250, relative).Unbox(pointerFactory, reader);
            ChrNetPhantomSoulRateParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrNetPhantomSoulRateParam>>(address + 0x00258, relative).Unbox(pointerFactory, reader);
            ChrModelParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrModelParam>>(address + 0x00260, relative).Unbox(pointerFactory, reader);
            EnemyShotSfxParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<EnemyShotSfxParam>>(address + 0x00268, relative).Unbox(pointerFactory, reader);
            ChrRoundDamageParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrRoundDamageParam>>(address + 0x00270, relative).Unbox(pointerFactory, reader);
            ChrRoundDropSoulParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrRoundDropSoulParam>>(address + 0x00278, relative).Unbox(pointerFactory, reader);
            ChrMultiplayParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<ChrMultiplayParam>>(address + 0x00280, relative).Unbox(pointerFactory, reader);
            FootEffectWaterSfxParam = pointerFactory.Create<ParamFileResourceObjectForRegulation<FootEffectWaterSfxParam>>(address + 0x00288, relative).Unbox(pointerFactory, reader);
            return this;
        }
    }
}
